version: 2.1

orbs:
  docker: circleci/docker@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12.3
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - docker/build:
          image: myapp
          tag: test
      - run:
          name: Run tests
          command: |
            docker run --rm myapp:test pytest --cov=src tests/
      - run:
          name: Copy test results
          command: |
            docker create --name test_container myapp:test
            docker cp test_container:/app/coverage.xml ./coverage.xml
            docker cp test_container:/app/.coverage ./.coverage
            docker rm test_container
          when: always
      - store_artifacts:
          path: coverage.xml
          destination: coverage-report
      - store_artifacts:
          path: .coverage
          destination: coverage-data
      - store_test_results:
          path: test-results

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
