version: 2.1

orbs:
  docker: circleci/docker@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12.3
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - docker/build:
          image: myapp-test-results
          tag: latest
          target: test-results
      - run:
          name: Extract test results
          command: |
            docker create --name temp_container myapp-test-results:latest
            docker cp temp_container:/coverage.xml ./coverage.xml
            docker rm temp_container
      - store_artifacts:
          path: coverage.xml
          destination: coverage-report
      - store_test_results:
          path: .
      - docker/build:
          image: myapp
          tag: latest

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
