version: 2.1

orbs:
  docker: circleci/docker@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12.3
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - docker/build:
          image: myapp
      - run:
          name: Run tests in Docker
          command: |
            docker run myapp pytest --cov=src tests

  deploy:
    docker:
      - image: cimg/python:3.12.3
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - docker/build:
          image: myapp
      - run:
          name: Deploy to production
          command: |
            # Здесь будут команды для деплоя
            echo "Deploying to production"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
