version: 2.1

orbs:
  docker: circleci/docker@2.1.1
  codecov: codecov/codecov@4.1.0

jobs:
  test:
    docker:
      - image: cimg/python:3.12.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt -r requirements-dev.txt
      - save_cache:
          paths:
            - ./venv
          key: deps-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            mkdir test-results
            pytest --cov=src --cov-report=xml:coverage.xml --junitxml=test-results/junit.xml tests/
      - store_artifacts:
          path: coverage.xml
          destination: coverage-report
      - store_test_results:
          path: test-results

  build:
    docker:
      - image: cimg/python:3.12.3
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - docker/build:
          image: myapp
          tag: latest

workflows:
  test-and-build:
    jobs:
      - test
      - codecov/upload:
          file: coverage.xml
          flags: unittests
      - build:
          requires:
            - test
          filters:
            branches:
              only: main
