version: 2.1

orbs:
  docker: circleci/docker@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12.3
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - docker/build:
          image: myapp
          tag: test
      - run:
          name: Run tests
          command: |
            docker create --name test_container myapp:test
            docker cp test_container:/app/. ./app_contents
            docker rm test_container
            cd app_contents
            pip install -r requirements-dev.txt
            pytest --cov=src tests/ || true
      - store_artifacts:
          path: app_contents/coverage.xml
          destination: coverage-report
      - store_test_results:
          path: app_contents/test-results

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
