jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12.3
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - docker/build:
          image: myapp
          tag: test
          target: builder # Собираем до этапа builder для тестов
      - run:
          name: Run tests
          command: |
            docker create --name test_container myapp:test
            docker cp test_container:/app/coverage.xml ./coverage.xml
            docker rm test_container
      - store_artifacts:
          path: coverage.xml
          destination: coverage-report

  build-and-push:
    docker:
      - image: cimg/python:3.12.3
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - docker/build:
          image: yourdockerhubusername/myapp
          tag: latest
      - docker/push:
          image: yourdockerhubusername/myapp
          tag: latest

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - build-and-push:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
